### ISSUE TITLE
can get this to work in titanium 

### ISSUE THREAD

**Issue by chris41188** [m1ga/tintimage#4]
Hi I am using this in my titanium project but I get a 
[WARN] :   TiDrawableReference: (KrollRuntimeThread) [0,71381] Could not open stream to get bitmap
error

here is my code

```
var blob1 = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory,'1400.jpg').read();
					
var itemTint = tint.tint({
    image: blob1,
    color: "#ff0000",
    mode: "multiply"
});
```

**Comment by m1ga** [comment]
I'll have a look at that. If you want to try a nightly build of the Ti SDK (5.4.x http://builds.appcelerator.com.s3.amazonaws.com/index.html) you won't need the module anymore. You can now use the normal tintColor on both platforms the same way (see https://jira.appcelerator.org/browse/TIMOB-19912 )

**Comment by chris41188** [comment]
Thanks for your reply
Yes I just found the tintColor am giving it a try

**Comment by chris41188** [comment]
Actually the  tintColor wont work for what I need as I need to set the mode to color,
tintcolor doesnt give you that option I think.

Actually I just need to convert an image quickly to grayscale so if you have any advice on how to get your module working that would be much appreciated

**Comment by m1ga** [comment]
I've tried your example above and it is working for me. There are two warnings which I'll remove in a future release (it's trying to open a mask image even there is none). Can you log blobq.exists() to check if the image is found?

**Comment by chris41188** [comment]
Thanks I have got it working now, is there anyway to tint an image to grayscale using this?

**Comment by m1ga** [comment]
`tint.grayscale({image:blob});` has been added to make it easy to convert to a grayscale image!

**Comment by chris41188** [comment]
Great! works like a charm, thank you so much for your help!
