### ISSUE TITLE
Not Supported.

### ISSUE THREAD

**Issue by saifdj** [m1ga/tintimage#5]
It is not supported by latest `7.0.1 GA` Titanium SDK, 
I have tried changing the version in mainfest file, after which i am getting the following error
`[ERROR] :  Could not find all required Titanium Modules:
[ERROR] :     id: miga.tintimage	 version: latest	 platform: android	 deploy-type: development`
Could you help on this

**Comment by m1ga** [comment]
sure, I've updated the module: https://github.com/m1ga/tintimage/blob/master/android/dist/miga.tintimage-android-3.0.0.zip
